name: flutter_flame_starter
description: Flutter Flame game starter with DDD feature-first architecture
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  flame: ^1.34.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  go_router: ^17.0.0
  hive_flutter: ^1.1.0
  intl: any
  json_annotation: ^4.9.0
  quick_log: ^5.5.3
  riverpod_annotation: ^3.0.3
  supabase_flutter: ^2.10.3

# Issue with analyzer_plugin version
# (https://github.com/dart-lang/sdk/issues/60784)
dependency_overrides:
  analyzer: ^9.0.0
  analyzer_plugin: ^0.13.11
  custom_lint_visitor: ^1.0.0+8.4.0

dev_dependencies:
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.3
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  generate: true
